"""empty message

Revision ID: 2427155f251e
Revises: None
Create Date: 2016-05-20 16:58:57.128879

"""

# revision identifiers, used by Alembic.
revision = '2427155f251e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
